Update releasing.yml

diff --git a/.github/workflows/releasing.yml b/.github/workflows/releasing.yml
--- a/.github/workflows/releasing.yml
+++ b/.github/workflows/releasing.yml
@@ -5,35 +5,81 @@ on:
     types: [published]
 
 jobs:
-    # based on https://github.com/pypa/gh-action-pypi-publish
-    release-pkg:
-        runs-on: ubuntu-20.04
-        timeout-minutes: 10
-        steps:
-            - name: Checkout 🛎️
-              uses: actions/checkout@v6
-            - name: Set up Python 🐍
-              uses: actions/setup-python@v5
-              with:
-                  python-version: 3.8
+  check_tag:
+    name: Check tag
+    runs-on: ubuntu-latest
 
-            - name: Create package 📦
-              run: |
-                  pip install "twine==5.1.1" setuptools wheel
-                  python setup.py sdist bdist_wheel
-                  ls -lh dist/
-                  twine check dist/*
+    steps:
+      - uses: actions/checkout@v6
 
-            - name: Upload to release
-              if: github.event_name == 'release'
-              uses: AButler/upload-release-assets@v3.0
-              with:
-                  files: "dist/*"
-                  repo-token: ${{ secrets.GITHUB_TOKEN }}
+      - uses: actions/setup-python@v6
+        with:
+          python-version: '3.11'
 
-            - name: Publish distribution 📦 to PyPI
-              if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
-              uses: pypa/gh-action-pypi-publish@v1.12.2
-              with:
-                  user: __token__
-                  password: ${{ secrets.pypi_password }}
+      - shell: bash
+        run: |
+          TAG="${{ github.event.release.tag_name }}"
+          GH_TAG_NAME="${TAG#v}"
+          PY_VERSION=$(python - <<'PY'
+          import pathlib, tomllib
+          data = tomllib.loads(pathlib.Path("pyproject.toml").read_text(encoding="utf-8"))
+          print(data.get("project").get("version"))
+          PY
+          )
+          if [ "${GH_TAG_NAME}" != "${PY_VERSION}" ]; then
+            echo "::error::Tag (${GH_TAG_NAME}) does not match pyproject.toml version (${PY_VERSION})."
+            exit 2
+          fi
+
+  build_wheels:
+    needs: check_tag
+    name: Build wheels
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v6
+
+      - name: Install uv
+        uses: astral-sh/setup-uv@v7
+        with:
+          enable-cache: true
+
+      - uses: actions/setup-python@v6
+        with:
+          python-version: '3.10'
+
+      - name: Build wheel
+        run: |
+          uv pip install build
+          uv build --wheel --sdist --out-dir wheelhouse
+        env:
+          UV_SYSTEM_PYTHON: 1
+
+      - name: Store wheels
+        uses: actions/upload-artifact@v6
+        with:
+          name: wheels
+          path: wheelhouse/*
+
+  # based on https://github.com/pypa/gh-action-pypi-publish
+  release-pkg:
+    runs-on: ubuntu-latest
+    needs: [build_wheels]
+
+    permissions:
+      id-token: write
+
+    timeout-minutes: 10
+    steps:
+      - uses: actions/download-artifact@v7
+        with:
+          name: wheels
+          path: wheelhouse
+
+      - name: Publish distribution 📦 to PyPI
+        uses: pypa/gh-action-pypi-publish@release/v1
+        with:
+            user: __token__
+            password: ${{ secrets.pypi_password }}
+            packages-dir: wheelhouse/
+
